synapsestudios/synfrastructure

components/button/_buttons.scss
components/button/button.jsx
mixins/synfrastructure-helper-mixin.js
scss/_settings.scss

Add button component

---

components/alert/_alerts.scss
components/alert/alert.jsx

Add alert components

---

components/button/button.jsx

Button component has a broken prop `modifier` that throws an error when passed as null

Button component has broken prop

---

components/button/ui-button.jsx

Fix button modifier error

---

components/form/inputs/ui-input.jsx
components/form/inputs/ui-select.jsx
components/form/inputs/ui-textarea.jsx
components/form/validation/ui-validation.jsx

1. Text inputs
1. Textarea
1. Select
1. Validation

Convert components to pure js

---

components/form/validation/ui-validation.jsx

1. Validation messages should have their own classNames

Fix validation message classes not rendering

---

components/form/inputs/ui-input.jsx

1.Inputs can render their own className prop

Fix input component props not being passed correctly

---

components/form/inputs/ui-input.jsx

1. Fix handlers on ui-input component

Fix input onChange, onFocus, onBlur handlers

---

components/form/validation/ui-validation.jsx

- validation prop should accept an object with a status string and a list of messages
- remove show prop

Fix validation components

---

components/form/inputs/ui-input.jsx
components/form/inputs/ui-select.jsx
components/form/inputs/ui-textarea.jsx
mixins/form-input-mixin.js

1. `onKeyDown onKeyUp onKeyPress` to all base form elements

Add keyboard events to form elements

---

.gitignore
.jshintrc
dist/alert.js
dist/button.js
dist/input.js
dist/label.js
dist/select.js
dist/textarea.js
dist/validation.js
package.json

1. `npm run build` compiles jsx files to `/dist` directory.
- {{list developer tasks here}}
- http://davidtheclark.com/building-react-aria-menubutton/
- https://github.com/davidtheclark/react-aria-menubutton

Build process : compile JSX to JS

---

demo/demo.jsx
dist/input.js
dist/select.js
dist/textarea.js
dist/validation.js
src/input.jsx
src/select.jsx
src/textarea.jsx
src/validation.jsx

Revert source components to JSX

---

index.js

- Export each React component so it can be required like `require ('synfrastructure').Component`

Add module exports for components

---

dist/select.js
package.json
src/select.jsx
webpack.config.demo.js

1. Run post processing on css file
1. Pipe in autoprefixer
1. Add css minification
- None
- None

Add postCSS postprocessor to webpack config

---

demo/demo.jsx
dist/modal.js
index.js
package.json
scss/app.scss
scss/components/_modals.scss
src/modal.jsx
util/className.js

1. Modal component is added to demo page
2. Modal component can display any component inside of it

Add Modal Component

---

demo/demo.jsx
dist/checkbox.js
index.js
src/checkbox.jsx

1. Add checkbox input
1. Accepts name, value, checked, event handlers and custom component css name

Add checkbox component

---

.eslintrc
.jshintrc
demo/demo.jsx
scss/app.scss
scss/components/_tooltips.scss
src/tooltip.jsx

1. Tooltips can be specified where they should appear relative to the icon
2. Examples are included
3. It's extensible and SCSS is variablized

Add tooltip component

---

demo/demo.jsx
scss/_synfrastructure.scss
scss/util/_animation-utilities.scss

1. Includes list of commonly-used animations
- Add to scss file

Add Animation SCSS utilities

---

src/button.jsx
src/checkbox.jsx
src/input.jsx
src/select.jsx
src/textarea.jsx

1. form inputs are able to receive a tab index property

Add tab index to form inputs

---

src/button.jsx
src/checkbox.jsx
src/input.jsx
src/select.jsx
src/textarea.jsx

Fix casing of tabIndex

---

demo/demo.jsx
scss/app.scss
scss/components/_switches.scss
src/modal.jsx
src/switch.jsx

1. Switches component added to synfrastructure

Add Switch Component

---

dist/checkbox.js
src/checkbox.jsx

making the onChange return the right value

---

demo/demo.jsx
dist/validation.js
src/validation.jsx

Remove validation prop

---

mixins/form-input-mixin.js

pass events for onFocus, onBlur, and onChange

Pass events in mixin

---

src/select.jsx

Allow user to pass disabled param for individual select options

Allow user to pass in a disabled property in the options list
